### ISSUE TITLE
A bug in inventory code patching?

### ISSUE THREAD

**Issue by laerreal** [DigglesMods/DwarfStatistics#1]
The patch I listed below is not working for me because there is line `set clst [list]` between `set x 90` and `set cnt 0`.
```
$start
$after
proc gnomeinfo_inventory {gid} {
	layout print "/(fn1)"
	layout print "/(ta10)[gnomename $gid]"
	layout print "/(fn0)/(ta80)/(bo-10)"
	set olst [inv_list $gid]
	set x 90
	set cnt 0

$put
	set lineCnt 0

$end
```
As a result `lineCnt` is uninitialized during the script execution and inventory is not shown.
Writing this patch in another way fixes it up.
```
$start
$after
proc gnomeinfo_inventory {gid} {
	layout print "/(fn1)"
	layout print "/(ta10)[gnomename $gid]"
	layout print "/(fn0)/(ta80)/(bo-10)"
	set olst [inv_list $gid]

$put
	set lineCnt 0

$end
```

Game version: 1.0.979.

**Comment by cech12** [comment]
Hey @laerreal !

Sorry for the late answer. I got no message about this issue. So thanks to @Aehrraid for assigning me. :)

Thanks for this bugfix. I added it in the [last commit](https://github.com/DigglesMods/DwarfStatistics/commit/1a492bad8fad80f1ab3760851c6d24eaa41a4643).

I have no access to the game version 1.0.979. So it is nice to hear, that the mods are also working with this game version. :)
